### ISSUE TITLE
[Installer] Fails to install in C:\Program Files (x86) on Windows 7

### ISSUE THREAD

**Issue by martinmoene** [MayaPosch/MQTTCute#5]
*MQTTCute* fails to install on drive `C:` in `C:\Program Files (x86)` under Windows 7.
It does however install on drive `D:` in `D:\Program Files (x86)`.
Installers for other programs are able to install in said directory on `C:`.

Details installer:
>Output folder: C:\Program Files (x86)\MQTTCute
>Can't write: C:\Program Files (x86)\MQTTCute\MQTTCute.exe

At this point, folder `MQTTCute` has not yet been created.

**Comment by MayaPosch** [comment]
The requested permission level in the installer script was set to 'user'. I have changed it to request Administrator level. A new installer binary has been uploaded (replacing the old one), which should install fine in special folders.

**Comment by martinmoene** [comment]
Thanks, that solves the issue.

**Comment by MayaPosch** [comment]
Thanks for confirming that it has been fixed :)
