### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by probonopd** [MayaPosch/MQTTCute#6]
Trying to make an AppImage, cannot compile due to compilation errors before AppImage generation even begins.

Travis CI Build script:
https://github.com/probonopd/MQTTCute/blob/d77ea6c9f54a7c33c4764feb188eb9a6a03c9297/.travis.yml

Log file:
https://travis-ci.com/probonopd/MQTTCute/builds/129765724

__Edit:__ No longer getting those errors (but others) now, the application seems to be coded using very recent versions of libraries rather than the versions that come with the oldest still-supported LTS distributions. Which means we need to compile those from source.

**Comment by MayaPosch** [comment]
Ubuntu Trusty comes with libpoco-dev 1.3.6: https://launchpad.net/ubuntu/trusty/+package/libpoco-dev

The 'initializeSSL()' function and others were first added in 1.4.0. The other errors are also likely due to this old version, as compiling it on Linux Mint 19.2 from the Github sources seems to work flawlessly.

Please retest with newer libPoco.

**Comment by probonopd** [comment]
__Edit:__ Thanks, trying with xenial and poco from source now.

**Comment by probonopd** [comment]
Still getting errors; does this mean I need to compile libpoco from source?

https://travis-ci.com/probonopd/MQTTCute/builds/129775235

**Comment by probonopd** [comment]
__Edit:__ Looks like compilation succeeded this time:
https://travis-ci.com/probonopd/MQTTCute/builds/129815306

But `make install` fails.

Is there a `mqttcute.desktop` and 256x256 px `mqttcute.png` already somewhere?

**Comment by probonopd** [comment]
`cannot find -lPocoJSON`, is it really needed?

**Comment by probonopd** [comment]
Getting `/usr/bin/ld: cannot find -lPocoJSON` now. Is that really needed?

**Comment by MrAureliusR** [comment]
@probonopd Just an aside, it's considered good etiquette to edit your first comment in any thread, as anyone who follows a particular project will get an individual email every time you comment. Just keep it in mind :)

**Comment by MayaPosch** [comment]
> 
>
> **Edit:** Looks like compilation succeeded this time:
> https://travis-ci.com/probonopd/MQTTCute/builds/129815306
> 
> But `make install` fails.
> 

There is at this moment no 'make install', because of the wide range of possible installation folders for binaries across distributions. The only product is the 'MQTTCute' binary, which can be copied by hand.

> Is there a `mqttcute.desktop` and 256x256 px `mqttcute.png` already somewhere?

The icon used by MQTTCute is the MQTT icon: https://github.com/MayaPosch/MQTTCute/tree/master/img

I assume a .desktop file would be a kind of desktop shortcut for Linux?

**Comment by probonopd** [comment]
Thanks @MayaPosch. Looks like I have an AppImage, but since I don't know the application well enough I don't know whether everything is working already. Maybe you'd like to give it a try:

https://github.com/probonopd/MQTTCute/releases/tag/continuous

In case it works, I'm happy to send a pull request that will produce and upload an AppImage using Travis CI.

**Comment by MayaPosch** [comment]
The AppImage works fine on a fresh Manjaro install at the very least, which is a good sign :)

I set up a Travis account as well (same username as on Github), so that could be used in the PR.

Thank you very much for your assistance! :)

**Comment by probonopd** [comment]
Thanks for testing @MayaPosch. PR sent, please see #7.

> I assume a .desktop file would be a kind of desktop shortcut for Linux?

It is what defines the name, icon, categories etc. to be used e.g., in menus. I made one as part of the pull request:

https://github.com/MayaPosch/MQTTCute/blob/256673707cb802b8e8268f9dbff5b6949ac23e08/mqttcute.desktop
